== Java EE 8: What's New in the Java EE 8 Release
=== David Delabassee
video::9VnVZ3j8yDQ[youtube]

===== Paul
This was an update on some of the new JEE 8 specifications, which was released earlier this year.
A few highlights:
* JAX-RS 2.1: better support for streams and asynchronous processing.
* JAX-RS 2.1: http reactive client with fluent api.
* JAX-RS 2.1: server sent events.
* JSON-P 1.1: Pointer (identify specific value within a json document)
* Servlet 4: HTTP/2 support with server push.
* CDI 2: support for asynchronous events.
* CDI 2: support for event listener ordering.

===== Hendrik
The title says it all: an overview of the things that are new. The new JAX-RS is very promising, it adds support for HTTP/2 and adds a very powerful `rx()` operation, for doing things asynchronously. JSON-P adds support for CRUD operations on JSON data structures without the need to parse everything first. The CDI library has been split up in different parts, so that is now quite simple to do CDI only for Java SE.

== gRPC vs REST: let the battle begin!
=== Alex Borysov & Mykyta Protsenko
video::ZDUA5pD50Ok[youtube]

===== Paul
gRPC is a new mechanism (devloped by Google) to communicate between services, that can be implemented as an alternative for using REST api's over HTTP.
In this talk several scenario's were discussed using gRPC or REST over HTTP.
gRPC is built with performance being a top priority.
Performance is more important than usability, which can be considered a characteristic of REST.
The use of formal (IDL) contracts with protocol buffers is mandatory.
It supports a variety of languages and tools can create stub code based on the contracts.

===== Hendrik
Google's RPC is a mature piece of software, because it has been open-sourced only recently after years of production withing Google. It uses protocol buffers over a formal protocol that you have to specify using the proto language. Basically it is some form of Interface Definition Language (IDL) known from stuff like CORBA. The proto compiler generates language bindings (Stubs) from the proto file, which you can then use in your software (in pieces that you want to connect with). 
The presenters did a shootout of both an implementation in classic REST and gRPC, with web app for guessing Pokemons and big data buzz words. Unfortunately, the gRPC implementation had some issue, causing it to crash. Due to all the hectic involved, it did not become apparent what the problem was. It was a perfect illustration of argument for REST: it is more simple and easier to track problems in.
O, BTW, REST is not JSON over HTTP ;-)

== The Diabolical Developer's Guide to Performance Tuning
=== Martijn Verburg
video::_y37cbS19JY[youtube]

===== Paul
Martijn Verburg runs a company (together with Kirk Pepperdine) called jClarity.
jClarity is specialised in analysing and solving performance problems.
They work with a simple method to give guidance about where to look for the problem.
A problem can occur at multiple levels: Operating system (including virtualisation), jvm, application.
He gave some pointers on where to start your investigation and how tools can help  with that.
It's very important to *measure* what the problem is, instead of guessing and maybe fixing something that is not the actual problem at hand.

== Globally Distributed Software Engineering - The Good, the Bad and the Ugly
==== Rini van Solingen
video:b9mrVHVC7WQ[youtube]

===== Hendrik
Rini van Solingen is a part-time professor at Delft University doing research on distributed software engineering. It showed from his whiteboard presentation: very clear. 
A few things stood out:
* research has shown that distributed software engineering starts at 50 meters! 
* if distributed development fails, culture is often blamed, in stead of the real problem. Company culture, professional culture and team culture are far more important (and influenceable!) than local culture.
* long learning curves (of on average 1.5 years) often collide with attrition. 

== Using Kotlin to implement Clean Architecture
=== Lieven Doclo
video::0wAvVcrbVK4[youtube]

===== Paul
This talk was divided in 2 parts: A brief description of Clean Architecture ("invented by Robert C. Martin") and a live demo using Kotlin.
In Clean Architecture it's very important to have several layers (like an union) that communicate with each other in only one direction.
A layer can only communicate with it's direct neighbour.
To make this possible we need to create different models in various layers.
For instance: The outer presentation layer doesn't "know" domain objects, but communicates using presentation objects.
Kotlin is pretty handy to create those different objects with a feature that is called "extension methods".

===== Hendrik
"Clean architecture" is somewhat of a hollow frase, especially with some not too clean diagrams. Anyway, the trick is to use "extension methods", where you'd normally have used static methods to translate between architectural layers.

== The Java Council
=== Simon Maple, Martijn Verburg, Oleg Šelajev
video::Iz6I3udrrkM[youtube]

*Time for beer!*
The Java Council is a podcast about Java.
This was an entertaining session.
First they showed the results of a survey that Zeroturnaround held across developers and made a couple of jokes, of course.
They also invented JDuchess to the floor which is celebrating it's 10 years anniversary.
JDuchess is a JUG (Java User Group) founded in The Netherlands.
The goal of this JUG is to support women in the software development industry.
Brian Goetz and Mark Reinhold were also invited on stage to answer some light developer questions.

===== Hendrik
Funny session with free beers ;-)

== Highway to Elm
=== Jordane Grenat
video::Ofx6LFCYea0[youtube]

===== Paul
We got an introduction to yet another programming language, called "Elm".
Elm "compiles" to javascript and therefore works on every major browser.
It's a typed language and it's killer feature is *No runtime exceptions*.
Error message during compilation / development are very clear and also come with suggestions about how to fix the problem.
The session was divided in two parts: explanation of the syntax / operations and a live coding demo.
A language worth looking into I would say.

===== Hendrik
Elm compiles Elm to JavaScript for creating code without exceptions. It is also a light-weight web framework, that makes use of sending messages to a model (some kind of state machine). You can communicate with existing JavaScript code on your page, via events (that you subscribe to beforehand).

== Opening Up Java EE: Panel Discussion
===  David Delabassee, Mike Croft, Dimitris Andreadis, Ivar Grimstad, Martijn Verburg, Roberto Cortez, Steve Poole
video::HRNskFH1MoU[youtube]

===== Paul
This was a very interesting panel discussion.
JEE (Java Enterprise Edition) is in the process of being moved from Oracle to The Eclipse Foundation.
That means that Oracle no longer decides about the future of JEE, but the community is.
No one knows were this will lead to yet, but it's struggling with a bad reputation now.
Hopefully this change will boost the community to create an even better platform.

===== Hendrik
Quite an insightful session about new EE4J Eclipse project, the new open sourced Java EE. After an initial EE4J 1.0 release, which will be identical to Java EE 8, it is the intention to deliver releases at a higher interval than has been done before. The big question is: isn't just too late for EE? Lots of companies have been building their own solutions based on existing (reference) implementations.

== The Rise of the Weaponized AI Propaganda Machine
=== Berit Anderson
video::PazlKN_FuWQ[youtube]

===== Paul

This was a call to action to do something against a worldwide network of "mind controlling" bots.
Those bots are believed to have greatly influenced the last U.S. presidential election and the Brexit referendum.
They use technology that is built over the last decade in Silicon Valley.
Facebook and Twitter were being flooded with targeted advertisements with the purpose to create chaos and put people against each other.
Berit also investigated why mr. Poetin would be involved in influencing the U.S. election and she made some good points explaining what she found out.

This network (still) is a major thread against western democracy.
The computational propaganda is so sophisticated that it is already able to fake a person's appearance on video.
That raises a lot of questions about *truth* and *free will*.

_Definitely worth the watch._

===== Hendrik
Berit Anderson from (https://scout.ai)[Scout] has done research on the use of human-controlled bots to influence people on Facebook to change their opinion. This has been done by both the Trump and Clinton campaigns, where Trump outnumbered Clinton by 5:1. The Russians are also involved in this new kind of "political marketing". They have probably been successful in influencing Brexit as well...
