The last day of the conference.
The exhibition floor was already cleared and the conference ended at 13:45.

== How to build an event-driven, dynamically re-configurable micro-services platform
=== Sven Beauprez
video::1D8hyLWMtfM[youtube]
===== Paul
This talk was about how a fin-tech company called "The Glue" built a system using micro-services on top of a datagrid.
The presenter told about:

* how they built auto-healing and backup services (by redeploying failing services on other machines).
* how the entire system is event-driven and backup of events, ensuring "one time processing".

===== Hendrik
This was one of the best presentations of the conference. The presenter works for a company called The Glue. They build a auto-reconfiguring Kubernetes, Dockerized, Apache Ignite grid that seems to have very high availability and performance. On top of that, it is transaction-safe as well.

== Blue Team Security. Actual Security work for Actual Developers
=== Siren Hofvander
video::yaLq88OjfoQ[youtube]
===== Paul
We're making the same mistakes over and over again.
The most likely attacker is some "script kiddie", not 'hacker dude".
What's the most risky thing that could happen?
Impact, Possibility and Ease of exploitation.
Don't have a database in clear text.
Start by drawing a thread model.
There's no defencee against "a stroke of genius" and "The 0-day horror".
Have a disaster recovery plan in place.s

* validate user inputs
** whitelisting input against a list of allowed characters
** boundery checking (data and number length)
** character escaping
** Check keys uniqueness and it actually exists

Take away: Start small. Rome wasn't built in one day.

== Safely Shoot Yourself in the Foot with Java 9
==== Heinz Kabutz
video:uk08-H_GtwI[youtube]

===== Hendrik
Heinz Kabutz likes to break things, especially those things that Oracle claims to have fixed.
With the introduction of Java 9, they have tried to minimize the use of Unsafe, they partly succeeded. With some runtime hacking Heinz Kabutz show how you can still make `System.out.println("Hello!")` print out `cheers`. Stuff you don't want to do in production ;-)

JVisualVM is gone from Java 8, but Netbean's open source Visual VM is (of course) still available on GitHub.

Nice to know: HashSet in Java 8 is not sorted. But is is, kind of, up until 56000 items. The hashing algorithm was simplified as a prevention to denial of service attacks.
In case you like puzzles like this, you should definitely subscribe to Heinz' mailing list.

== An introduction to JVM performance
=== Rafael Winterhalter
video::hjpzLXoUu1Y[youtube]
===== Paul
Every jvm does things different. This talk is about the hotspot jvm.
Javac doesn't do a lot of optimisation.
Optimisation happens at runtime in an adaptive manner.
The jvm finds hotspots (code that runs a lot) and optimises those accordingly.
Performance can be slow at first, because it needs to learn by profiling.

*Call sites* are places in the program that perform a method call
Every method call is virtual using virtual method tables.
Jvm optimisation can remove a virtual method call.
If you have 3 implementations of a class, a method call can be much more expensive.
Keep methods small, so runtime *inlining* (uber optimisation) is possible.
Write clearly structured programs using types to make the life of the compiler easier.
There's a great framework for benchmarking called JMH.

===== Hendrik
Very nice look into how the JVM HotSpot compiler works and optimizes code, based on profiling. The cool thing of the JVM is that is constantly optimizes code based on usage of an application. This may change over time. That is a big difference with, for example C++ code, where the programmer has to do the compiler tuning at build time, based on some profile. In case the profile changes, you'll have to manually change the parameters, rebuild and restart. The JVM gives you all this for free. It also explains why Java code many a time outperforms C code.

